//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiceSosyalHizmet.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuraninBilgileri
    {
        public long BasvuraninBilgileriID { get; set; }
        public string AdiSoyadi { get; set; }
        public string TC { get; set; }
        public string DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string BasvuruNedeni { get; set; }
        public string YardimAlaninAdiSoyadi { get; set; }
        public string YardimAlaninTC { get; set; }
        public string YardimAlaninDogumTarihi { get; set; }
        public string YardimAlaninYakinlikDurumu { get; set; }
        public string Durum { get; set; }
        public string MahalleKoy { get; set; }
        public string BasvuruTarihi { get; set; }
        public string OdemeSuresi { get; set; }
        public string OdemeBaslangici { get; set; }
        public string OdemeBitisi { get; set; }
        public string YBSNo { get; set; }
        public string ArsivNo { get; set; }
        public string DosyaTarihi { get; set; }
        public string Not { get; set; }
        public string DenetimTarihi { get; set; }
    }
}
