//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiceSosyalHizmet.Entity.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBChoiceEntities : DbContext
    {
        public DBChoiceEntities()
            : base("name=DBChoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasvuraninBilgileri> BasvuraninBilgileri { get; set; }
        public virtual DbSet<EBHDosyaTakip> EBHDosyaTakip { get; set; }
        public virtual DbSet<EngelliBilgileri> EngelliBilgileri { get; set; }
        public virtual DbSet<EvrakZimmetEBH> EvrakZimmetEBH { get; set; }
        public virtual DbSet<EvrakZimmetSED> EvrakZimmetSED { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<MahalleKoy> MahalleKoy { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<SEDDosyaTakip> SEDDosyaTakip { get; set; }
    }
}
