//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiceSosyalHizmet.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvrakZimmetSED
    {
        public long EvrakZimmetSEDID { get; set; }
        public long PersonelID { get; set; }
        public long BasvuraninBilgileriID { get; set; }
        public string Zimmettemi { get; set; }
        public string ZimmeteAlisTarihi { get; set; }
        public string ZimmettenCikisTarihi { get; set; }
    }
}
