//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiceSosyalHizmet.Entity.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public long PersonelID { get; set; }
        public string AdiSoyadi { get; set; }
        public string TC { get; set; }
    }
}
